[package]
name = "volt-ui"
version.workspace = true
edition.workspace = true

[dependencies]
winit = "0.30"
pollster = "0.3"
tokio = { workspace = true, features = ["rt", "sync"] }
volt-core = { path = "../volt-core" }
volt-renderer = { path = "../volt-renderer" }
volt-config = { path = "../volt-config" }
dirs = "5"
anyhow = { workspace = true }
