[package]
name = "volt-renderer"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
wgpu = "29"
winit = "0.30"
cosmic-text = "0.11"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.3"
tokio = { workspace = true, features = ["rt", "sync"] }
volt-core = { path = "../volt-core" }
volt-config = { path = "../volt-config" }
