[package]
name = "volt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A fast, GPU-accelerated terminal emulator"

[package.metadata.bundle]
name = "Volt"
identifier = "com.danieldear.volt"
icon = ["AppIcon.icns"]
short_description = "A fast, GPU-accelerated terminal emulator"
copyright = "Copyright © 2025 Daniel Dear. MIT License."
category = "developer-tool"

[[bin]]
name = "volt"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
volt-ui = { path = "../volt-ui" }
volt-config = { path = "../volt-config" }
