[package]
name = "volt-core"
version.workspace = true
edition.workspace = true

[dependencies]
vte = "0.13"
portable-pty = "0.8"
tokio = { workspace = true, features = ["rt", "sync", "io-util"] }
anyhow = { workspace = true }
volt-config = { path = "../volt-config" }
unicode-width = "0.2"
unicode-normalization = "0.1"
